// <auto-generated />
using System;
using HospitalManagementSystem.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HospitalManagementSystem.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260216174035_updatedrelation")]
    partial class updatedrelation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HospitalManagementSystem.Data.Models.Admission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AdmissionDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("BedId")
                        .HasColumnType("int");

                    b.Property<string>("DiagnosisAtAdmission")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DischargeDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DoctorId")
                        .HasColumnType("int");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BedId");

                    b.HasIndex("PatientId");

                    b.ToTable("Admissions");
                });

            modelBuilder.Entity("HospitalManagementSystem.Data.Models.ApplicationUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 31,
                            AccessFailedCount = 0,
                            Address = "Lahore, Pakistan",
                            Age = 40,
                            ConcurrencyStamp = "019f52cc-80b5-494f-9db9-8bcf210f3234",
                            Email = "admin@hms.com",
                            EmailConfirmed = true,
                            FirstName = "System",
                            Gender = "Male",
                            LastName = "Administrator",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@HMS.COM",
                            NormalizedUserName = "ADMIN@HMS.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEOM2G8P9XkY5TzR7LqV3WpZ9mN1vXc8Q==",
                            PhoneNumber = "03000000000",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "a3cfa07a-4ba9-48e9-9c0a-b7edc4987f49",
                            TwoFactorEnabled = false,
                            UserName = "admin@hms.com"
                        },
                        new
                        {
                            Id = 1,
                            AccessFailedCount = 0,
                            Address = "Lahore, Pakistan",
                            Age = 19,
                            ConcurrencyStamp = "07b7b54d-7205-4634-8504-41029b91b224",
                            Email = "user1@hms.com",
                            EmailConfirmed = true,
                            FirstName = "First1",
                            Gender = "Female",
                            LastName = "Demo",
                            LockoutEnabled = false,
                            NormalizedEmail = "USER1@HMS.COM",
                            NormalizedUserName = "USER1@HMS.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEOM2G8P9XkY5TzR7LqV3WpZ9mN1vXc8Q==",
                            PhoneNumber = "0300000001",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "92456c50-de71-44f3-833e-7ecd9fc073f3",
                            TwoFactorEnabled = false,
                            UserName = "user1@hms.com"
                        },
                        new
                        {
                            Id = 2,
                            AccessFailedCount = 0,
                            Address = "Lahore, Pakistan",
                            Age = 20,
                            ConcurrencyStamp = "00a24130-18ee-4794-9412-1cf8c4c1f459",
                            Email = "user2@hms.com",
                            EmailConfirmed = true,
                            FirstName = "First2",
                            Gender = "Male",
                            LastName = "Demo",
                            LockoutEnabled = false,
                            NormalizedEmail = "USER2@HMS.COM",
                            NormalizedUserName = "USER2@HMS.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEOM2G8P9XkY5TzR7LqV3WpZ9mN1vXc8Q==",
                            PhoneNumber = "0300000002",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "c8a41ef9-a1ec-4840-8d07-d5f735226771",
                            TwoFactorEnabled = false,
                            UserName = "user2@hms.com"
                        },
                        new
                        {
                            Id = 3,
                            AccessFailedCount = 0,
                            Address = "Lahore, Pakistan",
                            Age = 21,
                            ConcurrencyStamp = "220cdea8-5fd8-4f44-b4b0-8aa6d3183408",
                            Email = "user3@hms.com",
                            EmailConfirmed = true,
                            FirstName = "First3",
                            Gender = "Female",
                            LastName = "Demo",
                            LockoutEnabled = false,
                            NormalizedEmail = "USER3@HMS.COM",
                            NormalizedUserName = "USER3@HMS.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEOM2G8P9XkY5TzR7LqV3WpZ9mN1vXc8Q==",
                            PhoneNumber = "0300000003",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "35cb0aed-2165-48ae-8a15-84ef8fcbb62c",
                            TwoFactorEnabled = false,
                            UserName = "user3@hms.com"
                        },
                        new
                        {
                            Id = 4,
                            AccessFailedCount = 0,
                            Address = "Lahore, Pakistan",
                            Age = 22,
                            ConcurrencyStamp = "1afc0807-bdb9-46d0-91b0-0222fbe44aa1",
                            Email = "user4@hms.com",
                            EmailConfirmed = true,
                            FirstName = "First4",
                            Gender = "Male",
                            LastName = "Demo",
                            LockoutEnabled = false,
                            NormalizedEmail = "USER4@HMS.COM",
                            NormalizedUserName = "USER4@HMS.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEOM2G8P9XkY5TzR7LqV3WpZ9mN1vXc8Q==",
                            PhoneNumber = "0300000004",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "0693200f-6e9a-4468-9852-0f445269b551",
                            TwoFactorEnabled = false,
                            UserName = "user4@hms.com"
                        },
                        new
                        {
                            Id = 5,
                            AccessFailedCount = 0,
                            Address = "Lahore, Pakistan",
                            Age = 23,
                            ConcurrencyStamp = "5ad3646b-2eed-48d5-8a93-acad5e662b3b",
                            Email = "user5@hms.com",
                            EmailConfirmed = true,
                            FirstName = "First5",
                            Gender = "Female",
                            LastName = "Demo",
                            LockoutEnabled = false,
                            NormalizedEmail = "USER5@HMS.COM",
                            NormalizedUserName = "USER5@HMS.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEOM2G8P9XkY5TzR7LqV3WpZ9mN1vXc8Q==",
                            PhoneNumber = "0300000005",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "cf81ded2-75f4-4434-ad69-2b3cfa0ceede",
                            TwoFactorEnabled = false,
                            UserName = "user5@hms.com"
                        },
                        new
                        {
                            Id = 6,
                            AccessFailedCount = 0,
                            Address = "Lahore, Pakistan",
                            Age = 24,
                            ConcurrencyStamp = "f08cb824-cb7a-4d32-ba48-6080993c15f3",
                            Email = "user6@hms.com",
                            EmailConfirmed = true,
                            FirstName = "First6",
                            Gender = "Male",
                            LastName = "Demo",
                            LockoutEnabled = false,
                            NormalizedEmail = "USER6@HMS.COM",
                            NormalizedUserName = "USER6@HMS.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEOM2G8P9XkY5TzR7LqV3WpZ9mN1vXc8Q==",
                            PhoneNumber = "0300000006",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "9ce9e799-3227-4b63-97bd-9f7ac24ea658",
                            TwoFactorEnabled = false,
                            UserName = "user6@hms.com"
                        },
                        new
                        {
                            Id = 7,
                            AccessFailedCount = 0,
                            Address = "Lahore, Pakistan",
                            Age = 25,
                            ConcurrencyStamp = "d6d91cc7-4d17-490a-be28-fc51b788bc31",
                            Email = "user7@hms.com",
                            EmailConfirmed = true,
                            FirstName = "First7",
                            Gender = "Female",
                            LastName = "Demo",
                            LockoutEnabled = false,
                            NormalizedEmail = "USER7@HMS.COM",
                            NormalizedUserName = "USER7@HMS.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEOM2G8P9XkY5TzR7LqV3WpZ9mN1vXc8Q==",
                            PhoneNumber = "0300000007",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "3707963c-1e72-46c0-9369-a370a2cd5ba8",
                            TwoFactorEnabled = false,
                            UserName = "user7@hms.com"
                        },
                        new
                        {
                            Id = 8,
                            AccessFailedCount = 0,
                            Address = "Lahore, Pakistan",
                            Age = 26,
                            ConcurrencyStamp = "5766fcf0-19d2-4516-96c3-722690a5b86d",
                            Email = "user8@hms.com",
                            EmailConfirmed = true,
                            FirstName = "First8",
                            Gender = "Male",
                            LastName = "Demo",
                            LockoutEnabled = false,
                            NormalizedEmail = "USER8@HMS.COM",
                            NormalizedUserName = "USER8@HMS.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEOM2G8P9XkY5TzR7LqV3WpZ9mN1vXc8Q==",
                            PhoneNumber = "0300000008",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "b86823ed-7e55-4f96-af2c-d8ad8cc82eab",
                            TwoFactorEnabled = false,
                            UserName = "user8@hms.com"
                        },
                        new
                        {
                            Id = 9,
                            AccessFailedCount = 0,
                            Address = "Lahore, Pakistan",
                            Age = 27,
                            ConcurrencyStamp = "d09d9225-7df2-4e40-9c14-55307e55412c",
                            Email = "user9@hms.com",
                            EmailConfirmed = true,
                            FirstName = "First9",
                            Gender = "Female",
                            LastName = "Demo",
                            LockoutEnabled = false,
                            NormalizedEmail = "USER9@HMS.COM",
                            NormalizedUserName = "USER9@HMS.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEOM2G8P9XkY5TzR7LqV3WpZ9mN1vXc8Q==",
                            PhoneNumber = "0300000009",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "e020d48c-1616-4b44-ad0c-9da714df3750",
                            TwoFactorEnabled = false,
                            UserName = "user9@hms.com"
                        },
                        new
                        {
                            Id = 10,
                            AccessFailedCount = 0,
                            Address = "Lahore, Pakistan",
                            Age = 28,
                            ConcurrencyStamp = "28df0c04-90e6-465c-9a7f-6e460d6b17e8",
                            Email = "user10@hms.com",
                            EmailConfirmed = true,
                            FirstName = "First10",
                            Gender = "Male",
                            LastName = "Demo",
                            LockoutEnabled = false,
                            NormalizedEmail = "USER10@HMS.COM",
                            NormalizedUserName = "USER10@HMS.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEOM2G8P9XkY5TzR7LqV3WpZ9mN1vXc8Q==",
                            PhoneNumber = "0300000010",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "4f51e266-3698-42dc-84a8-7854f3ce0672",
                            TwoFactorEnabled = false,
                            UserName = "user10@hms.com"
                        },
                        new
                        {
                            Id = 11,
                            AccessFailedCount = 0,
                            Address = "Lahore, Pakistan",
                            Age = 29,
                            ConcurrencyStamp = "22d345be-91bf-4156-999f-1734253f053f",
                            Email = "user11@hms.com",
                            EmailConfirmed = true,
                            FirstName = "First11",
                            Gender = "Female",
                            LastName = "Demo",
                            LockoutEnabled = false,
                            NormalizedEmail = "USER11@HMS.COM",
                            NormalizedUserName = "USER11@HMS.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEOM2G8P9XkY5TzR7LqV3WpZ9mN1vXc8Q==",
                            PhoneNumber = "0300000011",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "7f53eaa1-40cb-41da-ac94-377486026a1d",
                            TwoFactorEnabled = false,
                            UserName = "user11@hms.com"
                        },
                        new
                        {
                            Id = 12,
                            AccessFailedCount = 0,
                            Address = "Lahore, Pakistan",
                            Age = 30,
                            ConcurrencyStamp = "6ce96c3f-fcf3-40d0-bb49-f3dca3c84329",
                            Email = "user12@hms.com",
                            EmailConfirmed = true,
                            FirstName = "First12",
                            Gender = "Male",
                            LastName = "Demo",
                            LockoutEnabled = false,
                            NormalizedEmail = "USER12@HMS.COM",
                            NormalizedUserName = "USER12@HMS.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEOM2G8P9XkY5TzR7LqV3WpZ9mN1vXc8Q==",
                            PhoneNumber = "0300000012",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "40c7b769-3a01-43d7-9349-9f99aa804fa3",
                            TwoFactorEnabled = false,
                            UserName = "user12@hms.com"
                        },
                        new
                        {
                            Id = 13,
                            AccessFailedCount = 0,
                            Address = "Lahore, Pakistan",
                            Age = 31,
                            ConcurrencyStamp = "ccf39d44-87f9-4f02-aad2-1a0692728df1",
                            Email = "user13@hms.com",
                            EmailConfirmed = true,
                            FirstName = "First13",
                            Gender = "Female",
                            LastName = "Demo",
                            LockoutEnabled = false,
                            NormalizedEmail = "USER13@HMS.COM",
                            NormalizedUserName = "USER13@HMS.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEOM2G8P9XkY5TzR7LqV3WpZ9mN1vXc8Q==",
                            PhoneNumber = "0300000013",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "764042bb-ad1c-49ee-bb56-25cc8f8b6b69",
                            TwoFactorEnabled = false,
                            UserName = "user13@hms.com"
                        },
                        new
                        {
                            Id = 14,
                            AccessFailedCount = 0,
                            Address = "Lahore, Pakistan",
                            Age = 32,
                            ConcurrencyStamp = "708d8397-f8c0-474a-8252-ce1a786b064d",
                            Email = "user14@hms.com",
                            EmailConfirmed = true,
                            FirstName = "First14",
                            Gender = "Male",
                            LastName = "Demo",
                            LockoutEnabled = false,
                            NormalizedEmail = "USER14@HMS.COM",
                            NormalizedUserName = "USER14@HMS.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEOM2G8P9XkY5TzR7LqV3WpZ9mN1vXc8Q==",
                            PhoneNumber = "0300000014",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "b1407244-3e73-4699-bedb-ea49470f8c20",
                            TwoFactorEnabled = false,
                            UserName = "user14@hms.com"
                        },
                        new
                        {
                            Id = 15,
                            AccessFailedCount = 0,
                            Address = "Lahore, Pakistan",
                            Age = 33,
                            ConcurrencyStamp = "76bd42fc-2b4b-47f6-802c-5812d615879d",
                            Email = "user15@hms.com",
                            EmailConfirmed = true,
                            FirstName = "First15",
                            Gender = "Female",
                            LastName = "Demo",
                            LockoutEnabled = false,
                            NormalizedEmail = "USER15@HMS.COM",
                            NormalizedUserName = "USER15@HMS.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEOM2G8P9XkY5TzR7LqV3WpZ9mN1vXc8Q==",
                            PhoneNumber = "0300000015",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "042035e1-c3f2-4ece-8514-c5175b545f05",
                            TwoFactorEnabled = false,
                            UserName = "user15@hms.com"
                        },
                        new
                        {
                            Id = 16,
                            AccessFailedCount = 0,
                            Address = "Lahore, Pakistan",
                            Age = 34,
                            ConcurrencyStamp = "f1d9cd68-b0b7-46cc-b1de-4badba786c31",
                            Email = "user16@hms.com",
                            EmailConfirmed = true,
                            FirstName = "First16",
                            Gender = "Male",
                            LastName = "Demo",
                            LockoutEnabled = false,
                            NormalizedEmail = "USER16@HMS.COM",
                            NormalizedUserName = "USER16@HMS.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEOM2G8P9XkY5TzR7LqV3WpZ9mN1vXc8Q==",
                            PhoneNumber = "0300000016",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "e72baef2-e0c2-4db3-bcc6-6bece0fa99dc",
                            TwoFactorEnabled = false,
                            UserName = "user16@hms.com"
                        },
                        new
                        {
                            Id = 17,
                            AccessFailedCount = 0,
                            Address = "Lahore, Pakistan",
                            Age = 35,
                            ConcurrencyStamp = "1c723412-9a3f-4e54-8a08-b176bd66527a",
                            Email = "user17@hms.com",
                            EmailConfirmed = true,
                            FirstName = "First17",
                            Gender = "Female",
                            LastName = "Demo",
                            LockoutEnabled = false,
                            NormalizedEmail = "USER17@HMS.COM",
                            NormalizedUserName = "USER17@HMS.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEOM2G8P9XkY5TzR7LqV3WpZ9mN1vXc8Q==",
                            PhoneNumber = "0300000017",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "f1a2cd59-63a2-4e44-b981-6e43429d9ffd",
                            TwoFactorEnabled = false,
                            UserName = "user17@hms.com"
                        },
                        new
                        {
                            Id = 18,
                            AccessFailedCount = 0,
                            Address = "Lahore, Pakistan",
                            Age = 36,
                            ConcurrencyStamp = "bb73c36c-b585-41c6-9c0f-837801c7b1a1",
                            Email = "user18@hms.com",
                            EmailConfirmed = true,
                            FirstName = "First18",
                            Gender = "Male",
                            LastName = "Demo",
                            LockoutEnabled = false,
                            NormalizedEmail = "USER18@HMS.COM",
                            NormalizedUserName = "USER18@HMS.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEOM2G8P9XkY5TzR7LqV3WpZ9mN1vXc8Q==",
                            PhoneNumber = "0300000018",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "1c6f9cda-efe5-4a88-804c-bd19df372ca8",
                            TwoFactorEnabled = false,
                            UserName = "user18@hms.com"
                        },
                        new
                        {
                            Id = 19,
                            AccessFailedCount = 0,
                            Address = "Lahore, Pakistan",
                            Age = 37,
                            ConcurrencyStamp = "f6f8ba54-52d9-40d1-81b0-efc47b8ce4cd",
                            Email = "user19@hms.com",
                            EmailConfirmed = true,
                            FirstName = "First19",
                            Gender = "Female",
                            LastName = "Demo",
                            LockoutEnabled = false,
                            NormalizedEmail = "USER19@HMS.COM",
                            NormalizedUserName = "USER19@HMS.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEOM2G8P9XkY5TzR7LqV3WpZ9mN1vXc8Q==",
                            PhoneNumber = "0300000019",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "18d3369c-4699-45d8-90e5-df6009a7ba4f",
                            TwoFactorEnabled = false,
                            UserName = "user19@hms.com"
                        },
                        new
                        {
                            Id = 20,
                            AccessFailedCount = 0,
                            Address = "Lahore, Pakistan",
                            Age = 38,
                            ConcurrencyStamp = "0e468a7c-a1ee-4917-b73f-2b3b5b075300",
                            Email = "user20@hms.com",
                            EmailConfirmed = true,
                            FirstName = "First20",
                            Gender = "Male",
                            LastName = "Demo",
                            LockoutEnabled = false,
                            NormalizedEmail = "USER20@HMS.COM",
                            NormalizedUserName = "USER20@HMS.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEOM2G8P9XkY5TzR7LqV3WpZ9mN1vXc8Q==",
                            PhoneNumber = "0300000020",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "bd2f6def-bf51-4e5b-8fc3-7621ba5625f2",
                            TwoFactorEnabled = false,
                            UserName = "user20@hms.com"
                        },
                        new
                        {
                            Id = 21,
                            AccessFailedCount = 0,
                            Address = "Lahore, Pakistan",
                            Age = 39,
                            ConcurrencyStamp = "ea44d7db-ba9a-4dae-bb4e-3aa0cb80c5f9",
                            Email = "user21@hms.com",
                            EmailConfirmed = true,
                            FirstName = "First21",
                            Gender = "Female",
                            LastName = "Demo",
                            LockoutEnabled = false,
                            NormalizedEmail = "USER21@HMS.COM",
                            NormalizedUserName = "USER21@HMS.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEOM2G8P9XkY5TzR7LqV3WpZ9mN1vXc8Q==",
                            PhoneNumber = "0300000021",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "31314fcc-10e9-40a0-b26a-d96e79ee07cd",
                            TwoFactorEnabled = false,
                            UserName = "user21@hms.com"
                        },
                        new
                        {
                            Id = 22,
                            AccessFailedCount = 0,
                            Address = "Lahore, Pakistan",
                            Age = 40,
                            ConcurrencyStamp = "f5644d30-4e04-47f5-bb40-d83b10015179",
                            Email = "user22@hms.com",
                            EmailConfirmed = true,
                            FirstName = "First22",
                            Gender = "Male",
                            LastName = "Demo",
                            LockoutEnabled = false,
                            NormalizedEmail = "USER22@HMS.COM",
                            NormalizedUserName = "USER22@HMS.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEOM2G8P9XkY5TzR7LqV3WpZ9mN1vXc8Q==",
                            PhoneNumber = "0300000022",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "285d0ec0-4092-4057-a8b7-13bec59a22fe",
                            TwoFactorEnabled = false,
                            UserName = "user22@hms.com"
                        },
                        new
                        {
                            Id = 23,
                            AccessFailedCount = 0,
                            Address = "Lahore, Pakistan",
                            Age = 41,
                            ConcurrencyStamp = "f90a5fb1-0bd2-4e0a-aa88-8e72879f5b3c",
                            Email = "user23@hms.com",
                            EmailConfirmed = true,
                            FirstName = "First23",
                            Gender = "Female",
                            LastName = "Demo",
                            LockoutEnabled = false,
                            NormalizedEmail = "USER23@HMS.COM",
                            NormalizedUserName = "USER23@HMS.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEOM2G8P9XkY5TzR7LqV3WpZ9mN1vXc8Q==",
                            PhoneNumber = "0300000023",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "fda34994-bc1f-4a69-a945-b09e06e84c9c",
                            TwoFactorEnabled = false,
                            UserName = "user23@hms.com"
                        },
                        new
                        {
                            Id = 24,
                            AccessFailedCount = 0,
                            Address = "Lahore, Pakistan",
                            Age = 42,
                            ConcurrencyStamp = "7a9171e9-f2b7-4ca2-8700-2b8326d1bb2e",
                            Email = "user24@hms.com",
                            EmailConfirmed = true,
                            FirstName = "First24",
                            Gender = "Male",
                            LastName = "Demo",
                            LockoutEnabled = false,
                            NormalizedEmail = "USER24@HMS.COM",
                            NormalizedUserName = "USER24@HMS.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEOM2G8P9XkY5TzR7LqV3WpZ9mN1vXc8Q==",
                            PhoneNumber = "0300000024",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "0476afc0-efe0-434b-b7eb-166c40a351bd",
                            TwoFactorEnabled = false,
                            UserName = "user24@hms.com"
                        },
                        new
                        {
                            Id = 25,
                            AccessFailedCount = 0,
                            Address = "Lahore, Pakistan",
                            Age = 43,
                            ConcurrencyStamp = "ebf9d4b8-3f2e-4655-a72a-cda5c8608725",
                            Email = "user25@hms.com",
                            EmailConfirmed = true,
                            FirstName = "First25",
                            Gender = "Female",
                            LastName = "Demo",
                            LockoutEnabled = false,
                            NormalizedEmail = "USER25@HMS.COM",
                            NormalizedUserName = "USER25@HMS.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEOM2G8P9XkY5TzR7LqV3WpZ9mN1vXc8Q==",
                            PhoneNumber = "0300000025",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "e917b5f4-f879-42fe-ac26-86d6bf168ae2",
                            TwoFactorEnabled = false,
                            UserName = "user25@hms.com"
                        },
                        new
                        {
                            Id = 26,
                            AccessFailedCount = 0,
                            Address = "Lahore, Pakistan",
                            Age = 44,
                            ConcurrencyStamp = "c4137a8d-266e-4844-a5f1-718036af942e",
                            Email = "user26@hms.com",
                            EmailConfirmed = true,
                            FirstName = "First26",
                            Gender = "Male",
                            LastName = "Demo",
                            LockoutEnabled = false,
                            NormalizedEmail = "USER26@HMS.COM",
                            NormalizedUserName = "USER26@HMS.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEOM2G8P9XkY5TzR7LqV3WpZ9mN1vXc8Q==",
                            PhoneNumber = "0300000026",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "72772777-f459-4ccd-bff9-978edf13c83d",
                            TwoFactorEnabled = false,
                            UserName = "user26@hms.com"
                        },
                        new
                        {
                            Id = 27,
                            AccessFailedCount = 0,
                            Address = "Lahore, Pakistan",
                            Age = 45,
                            ConcurrencyStamp = "c369d577-ab37-4856-a18c-5df545d2f394",
                            Email = "user27@hms.com",
                            EmailConfirmed = true,
                            FirstName = "First27",
                            Gender = "Female",
                            LastName = "Demo",
                            LockoutEnabled = false,
                            NormalizedEmail = "USER27@HMS.COM",
                            NormalizedUserName = "USER27@HMS.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEOM2G8P9XkY5TzR7LqV3WpZ9mN1vXc8Q==",
                            PhoneNumber = "0300000027",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "6a1fdce0-8fb2-4e74-b09a-85586272c79e",
                            TwoFactorEnabled = false,
                            UserName = "user27@hms.com"
                        },
                        new
                        {
                            Id = 28,
                            AccessFailedCount = 0,
                            Address = "Lahore, Pakistan",
                            Age = 46,
                            ConcurrencyStamp = "a71bdcb0-44ae-43c7-af62-c30b17c9a4dc",
                            Email = "user28@hms.com",
                            EmailConfirmed = true,
                            FirstName = "First28",
                            Gender = "Male",
                            LastName = "Demo",
                            LockoutEnabled = false,
                            NormalizedEmail = "USER28@HMS.COM",
                            NormalizedUserName = "USER28@HMS.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEOM2G8P9XkY5TzR7LqV3WpZ9mN1vXc8Q==",
                            PhoneNumber = "0300000028",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "6b58ed16-3281-489e-be96-f586d5c83085",
                            TwoFactorEnabled = false,
                            UserName = "user28@hms.com"
                        },
                        new
                        {
                            Id = 29,
                            AccessFailedCount = 0,
                            Address = "Lahore, Pakistan",
                            Age = 47,
                            ConcurrencyStamp = "0a6668d6-1f50-4a54-b06c-1696e657fc8c",
                            Email = "user29@hms.com",
                            EmailConfirmed = true,
                            FirstName = "First29",
                            Gender = "Female",
                            LastName = "Demo",
                            LockoutEnabled = false,
                            NormalizedEmail = "USER29@HMS.COM",
                            NormalizedUserName = "USER29@HMS.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEOM2G8P9XkY5TzR7LqV3WpZ9mN1vXc8Q==",
                            PhoneNumber = "0300000029",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "224bd4d6-5dcf-4834-a768-e1f445af3ced",
                            TwoFactorEnabled = false,
                            UserName = "user29@hms.com"
                        },
                        new
                        {
                            Id = 30,
                            AccessFailedCount = 0,
                            Address = "Lahore, Pakistan",
                            Age = 48,
                            ConcurrencyStamp = "608de6f5-647e-4d44-9acf-2a1a0f587bc9",
                            Email = "user30@hms.com",
                            EmailConfirmed = true,
                            FirstName = "First30",
                            Gender = "Male",
                            LastName = "Demo",
                            LockoutEnabled = false,
                            NormalizedEmail = "USER30@HMS.COM",
                            NormalizedUserName = "USER30@HMS.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEOM2G8P9XkY5TzR7LqV3WpZ9mN1vXc8Q==",
                            PhoneNumber = "0300000030",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "78c75147-8f8b-4435-b868-1912ad56207b",
                            TwoFactorEnabled = false,
                            UserName = "user30@hms.com"
                        });
                });

            modelBuilder.Entity("HospitalManagementSystem.Data.Models.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AppointmentDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.ToTable("Appointments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AppointmentDate = new DateTime(2025, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 1,
                            PatientId = 1,
                            Reason = "Routine checkup",
                            Status = "Confirmed"
                        },
                        new
                        {
                            Id = 2,
                            AppointmentDate = new DateTime(2025, 1, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 2,
                            PatientId = 2,
                            Reason = "Routine checkup",
                            Status = "Confirmed"
                        },
                        new
                        {
                            Id = 3,
                            AppointmentDate = new DateTime(2025, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 3,
                            PatientId = 3,
                            Reason = "Routine checkup",
                            Status = "Confirmed"
                        },
                        new
                        {
                            Id = 4,
                            AppointmentDate = new DateTime(2025, 1, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 4,
                            PatientId = 4,
                            Reason = "Routine checkup",
                            Status = "Confirmed"
                        },
                        new
                        {
                            Id = 5,
                            AppointmentDate = new DateTime(2025, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 5,
                            PatientId = 5,
                            Reason = "Routine checkup",
                            Status = "Confirmed"
                        });
                });

            modelBuilder.Entity("HospitalManagementSystem.Data.Models.Bed", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BedNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOccupied")
                        .HasColumnType("bit");

                    b.Property<int>("WardId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WardId");

                    b.ToTable("Beds");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BedNumber = "B-01",
                            IsDeleted = false,
                            IsOccupied = false,
                            WardId = 1
                        },
                        new
                        {
                            Id = 2,
                            BedNumber = "B-02",
                            IsDeleted = false,
                            IsOccupied = false,
                            WardId = 2
                        },
                        new
                        {
                            Id = 3,
                            BedNumber = "B-03",
                            IsDeleted = false,
                            IsOccupied = false,
                            WardId = 3
                        },
                        new
                        {
                            Id = 4,
                            BedNumber = "B-04",
                            IsDeleted = false,
                            IsOccupied = false,
                            WardId = 4
                        },
                        new
                        {
                            Id = 5,
                            BedNumber = "B-05",
                            IsDeleted = false,
                            IsOccupied = false,
                            WardId = 5
                        });
                });

            modelBuilder.Entity("HospitalManagementSystem.Data.Models.Bill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AppointmentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("BillingDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("bit");

                    b.Property<string>("PaymentMethod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Tax")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId");

                    b.ToTable("Bills");
                });

            modelBuilder.Entity("HospitalManagementSystem.Data.Models.BillItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("BillId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ReferenceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BillId");

                    b.ToTable("BillItems");
                });

            modelBuilder.Entity("HospitalManagementSystem.Data.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsDeleted = false,
                            Name = "Department 1"
                        },
                        new
                        {
                            Id = 2,
                            IsDeleted = false,
                            Name = "Department 2"
                        },
                        new
                        {
                            Id = 3,
                            IsDeleted = false,
                            Name = "Department 3"
                        },
                        new
                        {
                            Id = 4,
                            IsDeleted = false,
                            Name = "Department 4"
                        },
                        new
                        {
                            Id = 5,
                            IsDeleted = false,
                            Name = "Department 5"
                        });
                });

            modelBuilder.Entity("HospitalManagementSystem.Data.Models.Doctor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("ConsultationFee")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Qualification")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Doctors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConsultationFee = 2000m,
                            DepartmentId = 1,
                            Specialization = "Specialty 1",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            ConsultationFee = 2200m,
                            DepartmentId = 2,
                            Specialization = "Specialty 2",
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            ConsultationFee = 2400m,
                            DepartmentId = 3,
                            Specialization = "Specialty 3",
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            ConsultationFee = 2600m,
                            DepartmentId = 4,
                            Specialization = "Specialty 4",
                            UserId = 4
                        },
                        new
                        {
                            Id = 5,
                            ConsultationFee = 2800m,
                            DepartmentId = 5,
                            Specialization = "Specialty 5",
                            UserId = 5
                        });
                });

            modelBuilder.Entity("HospitalManagementSystem.Data.Models.LabReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("LabTestId")
                        .HasColumnType("int");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("ResultDetails")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TestDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("LabTestId");

                    b.HasIndex("PatientId");

                    b.ToTable("LabReports");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsDeleted = false,
                            LabTestId = 1,
                            PatientId = 1,
                            ResultDetails = "Within normal limits",
                            TestDate = new DateTime(2025, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            IsDeleted = false,
                            LabTestId = 2,
                            PatientId = 2,
                            ResultDetails = "Within normal limits",
                            TestDate = new DateTime(2025, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            IsDeleted = false,
                            LabTestId = 3,
                            PatientId = 3,
                            ResultDetails = "Within normal limits",
                            TestDate = new DateTime(2025, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            IsDeleted = false,
                            LabTestId = 4,
                            PatientId = 4,
                            ResultDetails = "Within normal limits",
                            TestDate = new DateTime(2025, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            IsDeleted = false,
                            LabTestId = 5,
                            PatientId = 5,
                            ResultDetails = "Within normal limits",
                            TestDate = new DateTime(2025, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("HospitalManagementSystem.Data.Models.LabTest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TestName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LabTests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsDeleted = false,
                            Price = 950m,
                            TestName = "Lab Test 1"
                        },
                        new
                        {
                            Id = 2,
                            IsDeleted = false,
                            Price = 1100m,
                            TestName = "Lab Test 2"
                        },
                        new
                        {
                            Id = 3,
                            IsDeleted = false,
                            Price = 1250m,
                            TestName = "Lab Test 3"
                        },
                        new
                        {
                            Id = 4,
                            IsDeleted = false,
                            Price = 1400m,
                            TestName = "Lab Test 4"
                        },
                        new
                        {
                            Id = 5,
                            IsDeleted = false,
                            Price = 1550m,
                            TestName = "Lab Test 5"
                        });
                });

            modelBuilder.Entity("HospitalManagementSystem.Data.Models.MedicalRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Diagnosis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("Symptoms")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TreatmentPlan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.ToTable("MedicalRecords");
                });

            modelBuilder.Entity("HospitalManagementSystem.Data.Models.Medicine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Medicines");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ExpiryDate = new DateTime(2027, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "Medicine 1",
                            StockQuantity = 200,
                            UnitPrice = 45.50m
                        },
                        new
                        {
                            Id = 2,
                            ExpiryDate = new DateTime(2027, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "Medicine 2",
                            StockQuantity = 200,
                            UnitPrice = 91.00m
                        },
                        new
                        {
                            Id = 3,
                            ExpiryDate = new DateTime(2027, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "Medicine 3",
                            StockQuantity = 200,
                            UnitPrice = 136.50m
                        },
                        new
                        {
                            Id = 4,
                            ExpiryDate = new DateTime(2027, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "Medicine 4",
                            StockQuantity = 200,
                            UnitPrice = 182.00m
                        },
                        new
                        {
                            Id = 5,
                            ExpiryDate = new DateTime(2027, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "Medicine 5",
                            StockQuantity = 200,
                            UnitPrice = 227.50m
                        });
                });

            modelBuilder.Entity("HospitalManagementSystem.Data.Models.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BloodGroup")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmergencyContact")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Patients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BloodGroup = "A+",
                            IsDeleted = false,
                            UserId = 11
                        },
                        new
                        {
                            Id = 2,
                            BloodGroup = "B+",
                            IsDeleted = false,
                            UserId = 12
                        },
                        new
                        {
                            Id = 3,
                            BloodGroup = "O+",
                            IsDeleted = false,
                            UserId = 13
                        },
                        new
                        {
                            Id = 4,
                            BloodGroup = "A+",
                            IsDeleted = false,
                            UserId = 14
                        },
                        new
                        {
                            Id = 5,
                            BloodGroup = "B+",
                            IsDeleted = false,
                            UserId = 15
                        });
                });

            modelBuilder.Entity("HospitalManagementSystem.Data.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("BillId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransactionId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BillId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("HospitalManagementSystem.Data.Models.Prescription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MedicalRecordId")
                        .HasColumnType("int");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PrescriptionDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.ToTable("Prescriptions");
                });

            modelBuilder.Entity("HospitalManagementSystem.Data.Models.PrescriptionItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Dosage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MedicineId")
                        .HasColumnType("int");

                    b.Property<int>("PrescriptionId")
                        .HasColumnType("int");

                    b.Property<decimal?>("PriceAtIssue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MedicineId");

                    b.HasIndex("PrescriptionId");

                    b.ToTable("PrescriptionItems");
                });

            modelBuilder.Entity("HospitalManagementSystem.Data.Models.Staff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal>("Salary")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("StaffMembers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Designation = "Technician",
                            IsDeleted = false,
                            Salary = 53000m,
                            UserId = 21
                        },
                        new
                        {
                            Id = 2,
                            Designation = "Nurse",
                            IsDeleted = false,
                            Salary = 58000m,
                            UserId = 22
                        },
                        new
                        {
                            Id = 3,
                            Designation = "Technician",
                            IsDeleted = false,
                            Salary = 63000m,
                            UserId = 23
                        },
                        new
                        {
                            Id = 4,
                            Designation = "Nurse",
                            IsDeleted = false,
                            Salary = 68000m,
                            UserId = 24
                        },
                        new
                        {
                            Id = 5,
                            Designation = "Technician",
                            IsDeleted = false,
                            Salary = 73000m,
                            UserId = 25
                        });
                });

            modelBuilder.Entity("HospitalManagementSystem.Data.Models.Ward", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalBeds")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Wards");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsDeleted = false,
                            Name = "Ward 1",
                            TotalBeds = 12,
                            Type = "Special"
                        },
                        new
                        {
                            Id = 2,
                            IsDeleted = false,
                            Name = "Ward 2",
                            TotalBeds = 12,
                            Type = "General"
                        },
                        new
                        {
                            Id = 3,
                            IsDeleted = false,
                            Name = "Ward 3",
                            TotalBeds = 12,
                            Type = "Special"
                        },
                        new
                        {
                            Id = 4,
                            IsDeleted = false,
                            Name = "Ward 4",
                            TotalBeds = 12,
                            Type = "General"
                        },
                        new
                        {
                            Id = 5,
                            IsDeleted = false,
                            Name = "Ward 5",
                            TotalBeds = 12,
                            Type = "Special"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Doctor",
                            NormalizedName = "DOCTOR"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Patient",
                            NormalizedName = "PATIENT"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Staff",
                            NormalizedName = "STAFF"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = 31,
                            RoleId = 1
                        },
                        new
                        {
                            UserId = 1,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 2,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 3,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 4,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 5,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 6,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 7,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 8,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 9,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 10,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 11,
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 12,
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 13,
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 14,
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 15,
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 16,
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 17,
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 18,
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 19,
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 20,
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 21,
                            RoleId = 4
                        },
                        new
                        {
                            UserId = 22,
                            RoleId = 4
                        },
                        new
                        {
                            UserId = 23,
                            RoleId = 4
                        },
                        new
                        {
                            UserId = 24,
                            RoleId = 4
                        },
                        new
                        {
                            UserId = 25,
                            RoleId = 4
                        },
                        new
                        {
                            UserId = 26,
                            RoleId = 4
                        },
                        new
                        {
                            UserId = 27,
                            RoleId = 4
                        },
                        new
                        {
                            UserId = 28,
                            RoleId = 4
                        },
                        new
                        {
                            UserId = 29,
                            RoleId = 4
                        },
                        new
                        {
                            UserId = 30,
                            RoleId = 4
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("HospitalManagementSystem.Data.Models.Admission", b =>
                {
                    b.HasOne("HospitalManagementSystem.Data.Models.Bed", "Bed")
                        .WithMany("Admissions")
                        .HasForeignKey("BedId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HospitalManagementSystem.Data.Models.Patient", "Patient")
                        .WithMany("Admissions")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Bed");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("HospitalManagementSystem.Data.Models.Appointment", b =>
                {
                    b.HasOne("HospitalManagementSystem.Data.Models.Doctor", "Doctor")
                        .WithMany("Appointments")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HospitalManagementSystem.Data.Models.Patient", "Patient")
                        .WithMany("Appointments")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("HospitalManagementSystem.Data.Models.Bed", b =>
                {
                    b.HasOne("HospitalManagementSystem.Data.Models.Ward", "Ward")
                        .WithMany("Beds")
                        .HasForeignKey("WardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ward");
                });

            modelBuilder.Entity("HospitalManagementSystem.Data.Models.Bill", b =>
                {
                    b.HasOne("HospitalManagementSystem.Data.Models.Appointment", "Appointment")
                        .WithMany()
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Appointment");
                });

            modelBuilder.Entity("HospitalManagementSystem.Data.Models.BillItem", b =>
                {
                    b.HasOne("HospitalManagementSystem.Data.Models.Bill", "Bill")
                        .WithMany("Items")
                        .HasForeignKey("BillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bill");
                });

            modelBuilder.Entity("HospitalManagementSystem.Data.Models.Doctor", b =>
                {
                    b.HasOne("HospitalManagementSystem.Data.Models.Department", "Department")
                        .WithMany("Doctors")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HospitalManagementSystem.Data.Models.ApplicationUser", "User")
                        .WithOne()
                        .HasForeignKey("HospitalManagementSystem.Data.Models.Doctor", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HospitalManagementSystem.Data.Models.LabReport", b =>
                {
                    b.HasOne("HospitalManagementSystem.Data.Models.LabTest", "LabTest")
                        .WithMany()
                        .HasForeignKey("LabTestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HospitalManagementSystem.Data.Models.Patient", "Patient")
                        .WithMany("LabReports")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LabTest");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("HospitalManagementSystem.Data.Models.MedicalRecord", b =>
                {
                    b.HasOne("HospitalManagementSystem.Data.Models.Doctor", "Doctor")
                        .WithMany("MedicalRecords")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HospitalManagementSystem.Data.Models.Patient", "Patient")
                        .WithMany("MedicalRecords")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("HospitalManagementSystem.Data.Models.Patient", b =>
                {
                    b.HasOne("HospitalManagementSystem.Data.Models.ApplicationUser", "User")
                        .WithOne()
                        .HasForeignKey("HospitalManagementSystem.Data.Models.Patient", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HospitalManagementSystem.Data.Models.Payment", b =>
                {
                    b.HasOne("HospitalManagementSystem.Data.Models.Bill", "Bill")
                        .WithMany("Payments")
                        .HasForeignKey("BillId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Bill");
                });

            modelBuilder.Entity("HospitalManagementSystem.Data.Models.Prescription", b =>
                {
                    b.HasOne("HospitalManagementSystem.Data.Models.Doctor", "Doctor")
                        .WithMany("Prescriptions")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HospitalManagementSystem.Data.Models.Patient", "Patient")
                        .WithMany("Prescriptions")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("HospitalManagementSystem.Data.Models.PrescriptionItem", b =>
                {
                    b.HasOne("HospitalManagementSystem.Data.Models.Medicine", "Medicine")
                        .WithMany()
                        .HasForeignKey("MedicineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HospitalManagementSystem.Data.Models.Prescription", "Prescription")
                        .WithMany("Items")
                        .HasForeignKey("PrescriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Medicine");

                    b.Navigation("Prescription");
                });

            modelBuilder.Entity("HospitalManagementSystem.Data.Models.Staff", b =>
                {
                    b.HasOne("HospitalManagementSystem.Data.Models.ApplicationUser", "User")
                        .WithOne()
                        .HasForeignKey("HospitalManagementSystem.Data.Models.Staff", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("HospitalManagementSystem.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("HospitalManagementSystem.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HospitalManagementSystem.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("HospitalManagementSystem.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HospitalManagementSystem.Data.Models.Bed", b =>
                {
                    b.Navigation("Admissions");
                });

            modelBuilder.Entity("HospitalManagementSystem.Data.Models.Bill", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("HospitalManagementSystem.Data.Models.Department", b =>
                {
                    b.Navigation("Doctors");
                });

            modelBuilder.Entity("HospitalManagementSystem.Data.Models.Doctor", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("MedicalRecords");

                    b.Navigation("Prescriptions");
                });

            modelBuilder.Entity("HospitalManagementSystem.Data.Models.Patient", b =>
                {
                    b.Navigation("Admissions");

                    b.Navigation("Appointments");

                    b.Navigation("LabReports");

                    b.Navigation("MedicalRecords");

                    b.Navigation("Prescriptions");
                });

            modelBuilder.Entity("HospitalManagementSystem.Data.Models.Prescription", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("HospitalManagementSystem.Data.Models.Ward", b =>
                {
                    b.Navigation("Beds");
                });
#pragma warning restore 612, 618
        }
    }
}
