// <auto-generated />
using System;
using HospitalManagementSystem.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HospitalManagementSystem.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260216173725_updatedrelations")]
    partial class updatedrelations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HospitalManagementSystem.Data.Models.Admission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AdmissionDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("BedId")
                        .HasColumnType("int");

                    b.Property<string>("DiagnosisAtAdmission")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DischargeDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DoctorId")
                        .HasColumnType("int");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BedId");

                    b.HasIndex("PatientId");

                    b.ToTable("Admissions");
                });

            modelBuilder.Entity("HospitalManagementSystem.Data.Models.ApplicationUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 31,
                            AccessFailedCount = 0,
                            Address = "Lahore, Pakistan",
                            Age = 40,
                            ConcurrencyStamp = "2adc1114-2d97-4338-b98d-d180c746e886",
                            Email = "admin@hms.com",
                            EmailConfirmed = true,
                            FirstName = "System",
                            Gender = "Male",
                            LastName = "Administrator",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@HMS.COM",
                            NormalizedUserName = "ADMIN@HMS.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEOM2G8P9XkY5TzR7LqV3WpZ9mN1vXc8Q==",
                            PhoneNumber = "03000000000",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "d0bfd930-b066-48c6-9e7b-1c6f266d6d24",
                            TwoFactorEnabled = false,
                            UserName = "admin@hms.com"
                        },
                        new
                        {
                            Id = 1,
                            AccessFailedCount = 0,
                            Address = "Lahore, Pakistan",
                            Age = 19,
                            ConcurrencyStamp = "86a68204-03f4-4d7e-9f63-fec3f89ccaa4",
                            Email = "user1@hms.com",
                            EmailConfirmed = true,
                            FirstName = "First1",
                            Gender = "Female",
                            LastName = "Demo",
                            LockoutEnabled = false,
                            NormalizedEmail = "USER1@HMS.COM",
                            NormalizedUserName = "USER1@HMS.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEOM2G8P9XkY5TzR7LqV3WpZ9mN1vXc8Q==",
                            PhoneNumber = "0300000001",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "0621ca05-caa2-440e-a1b5-33aa974003b0",
                            TwoFactorEnabled = false,
                            UserName = "user1@hms.com"
                        },
                        new
                        {
                            Id = 2,
                            AccessFailedCount = 0,
                            Address = "Lahore, Pakistan",
                            Age = 20,
                            ConcurrencyStamp = "0ab45c46-7c5c-40a8-83cc-33d759d46e5e",
                            Email = "user2@hms.com",
                            EmailConfirmed = true,
                            FirstName = "First2",
                            Gender = "Male",
                            LastName = "Demo",
                            LockoutEnabled = false,
                            NormalizedEmail = "USER2@HMS.COM",
                            NormalizedUserName = "USER2@HMS.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEOM2G8P9XkY5TzR7LqV3WpZ9mN1vXc8Q==",
                            PhoneNumber = "0300000002",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "eb2be4ec-6151-4e11-9a6d-f9a0c243d712",
                            TwoFactorEnabled = false,
                            UserName = "user2@hms.com"
                        },
                        new
                        {
                            Id = 3,
                            AccessFailedCount = 0,
                            Address = "Lahore, Pakistan",
                            Age = 21,
                            ConcurrencyStamp = "0400103d-beaa-4921-bd8f-52ad3ca3a0a1",
                            Email = "user3@hms.com",
                            EmailConfirmed = true,
                            FirstName = "First3",
                            Gender = "Female",
                            LastName = "Demo",
                            LockoutEnabled = false,
                            NormalizedEmail = "USER3@HMS.COM",
                            NormalizedUserName = "USER3@HMS.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEOM2G8P9XkY5TzR7LqV3WpZ9mN1vXc8Q==",
                            PhoneNumber = "0300000003",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "91f21fc5-0c97-41b1-b08e-1e3b958706e2",
                            TwoFactorEnabled = false,
                            UserName = "user3@hms.com"
                        },
                        new
                        {
                            Id = 4,
                            AccessFailedCount = 0,
                            Address = "Lahore, Pakistan",
                            Age = 22,
                            ConcurrencyStamp = "4268ec6d-8501-4228-ba69-5a987c82c5d0",
                            Email = "user4@hms.com",
                            EmailConfirmed = true,
                            FirstName = "First4",
                            Gender = "Male",
                            LastName = "Demo",
                            LockoutEnabled = false,
                            NormalizedEmail = "USER4@HMS.COM",
                            NormalizedUserName = "USER4@HMS.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEOM2G8P9XkY5TzR7LqV3WpZ9mN1vXc8Q==",
                            PhoneNumber = "0300000004",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "54937e5d-a557-485d-9b29-d807cb307771",
                            TwoFactorEnabled = false,
                            UserName = "user4@hms.com"
                        },
                        new
                        {
                            Id = 5,
                            AccessFailedCount = 0,
                            Address = "Lahore, Pakistan",
                            Age = 23,
                            ConcurrencyStamp = "d3357f87-6cc0-448d-9b81-2b940afdad23",
                            Email = "user5@hms.com",
                            EmailConfirmed = true,
                            FirstName = "First5",
                            Gender = "Female",
                            LastName = "Demo",
                            LockoutEnabled = false,
                            NormalizedEmail = "USER5@HMS.COM",
                            NormalizedUserName = "USER5@HMS.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEOM2G8P9XkY5TzR7LqV3WpZ9mN1vXc8Q==",
                            PhoneNumber = "0300000005",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "dfeddd52-9cff-470d-90fc-24ef93ab180e",
                            TwoFactorEnabled = false,
                            UserName = "user5@hms.com"
                        },
                        new
                        {
                            Id = 6,
                            AccessFailedCount = 0,
                            Address = "Lahore, Pakistan",
                            Age = 24,
                            ConcurrencyStamp = "9b099fa5-6b76-4e54-87e1-9a681fb943f8",
                            Email = "user6@hms.com",
                            EmailConfirmed = true,
                            FirstName = "First6",
                            Gender = "Male",
                            LastName = "Demo",
                            LockoutEnabled = false,
                            NormalizedEmail = "USER6@HMS.COM",
                            NormalizedUserName = "USER6@HMS.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEOM2G8P9XkY5TzR7LqV3WpZ9mN1vXc8Q==",
                            PhoneNumber = "0300000006",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "8fd59893-56e7-4efb-b6c1-8de902cc4f09",
                            TwoFactorEnabled = false,
                            UserName = "user6@hms.com"
                        },
                        new
                        {
                            Id = 7,
                            AccessFailedCount = 0,
                            Address = "Lahore, Pakistan",
                            Age = 25,
                            ConcurrencyStamp = "b91dca52-efc2-4da6-be56-a246a4746d3f",
                            Email = "user7@hms.com",
                            EmailConfirmed = true,
                            FirstName = "First7",
                            Gender = "Female",
                            LastName = "Demo",
                            LockoutEnabled = false,
                            NormalizedEmail = "USER7@HMS.COM",
                            NormalizedUserName = "USER7@HMS.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEOM2G8P9XkY5TzR7LqV3WpZ9mN1vXc8Q==",
                            PhoneNumber = "0300000007",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "2866d24c-dceb-4a60-a28f-39dc6d359a8c",
                            TwoFactorEnabled = false,
                            UserName = "user7@hms.com"
                        },
                        new
                        {
                            Id = 8,
                            AccessFailedCount = 0,
                            Address = "Lahore, Pakistan",
                            Age = 26,
                            ConcurrencyStamp = "be9699fd-e58e-42e2-85aa-d1a5d6bccd42",
                            Email = "user8@hms.com",
                            EmailConfirmed = true,
                            FirstName = "First8",
                            Gender = "Male",
                            LastName = "Demo",
                            LockoutEnabled = false,
                            NormalizedEmail = "USER8@HMS.COM",
                            NormalizedUserName = "USER8@HMS.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEOM2G8P9XkY5TzR7LqV3WpZ9mN1vXc8Q==",
                            PhoneNumber = "0300000008",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "721776d1-c874-47c3-a13a-8799b95c54c7",
                            TwoFactorEnabled = false,
                            UserName = "user8@hms.com"
                        },
                        new
                        {
                            Id = 9,
                            AccessFailedCount = 0,
                            Address = "Lahore, Pakistan",
                            Age = 27,
                            ConcurrencyStamp = "d5327041-8909-43b8-af0a-621dee555988",
                            Email = "user9@hms.com",
                            EmailConfirmed = true,
                            FirstName = "First9",
                            Gender = "Female",
                            LastName = "Demo",
                            LockoutEnabled = false,
                            NormalizedEmail = "USER9@HMS.COM",
                            NormalizedUserName = "USER9@HMS.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEOM2G8P9XkY5TzR7LqV3WpZ9mN1vXc8Q==",
                            PhoneNumber = "0300000009",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "9cbd60e3-e8e8-450b-bf79-e70a2472afbb",
                            TwoFactorEnabled = false,
                            UserName = "user9@hms.com"
                        },
                        new
                        {
                            Id = 10,
                            AccessFailedCount = 0,
                            Address = "Lahore, Pakistan",
                            Age = 28,
                            ConcurrencyStamp = "fd94599d-8575-4a19-b028-284c95867837",
                            Email = "user10@hms.com",
                            EmailConfirmed = true,
                            FirstName = "First10",
                            Gender = "Male",
                            LastName = "Demo",
                            LockoutEnabled = false,
                            NormalizedEmail = "USER10@HMS.COM",
                            NormalizedUserName = "USER10@HMS.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEOM2G8P9XkY5TzR7LqV3WpZ9mN1vXc8Q==",
                            PhoneNumber = "0300000010",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "138fb09c-1ee8-4f8a-a44a-12549f1e751b",
                            TwoFactorEnabled = false,
                            UserName = "user10@hms.com"
                        },
                        new
                        {
                            Id = 11,
                            AccessFailedCount = 0,
                            Address = "Lahore, Pakistan",
                            Age = 29,
                            ConcurrencyStamp = "0e8f937e-74b9-42fb-ac12-09e1197f7f36",
                            Email = "user11@hms.com",
                            EmailConfirmed = true,
                            FirstName = "First11",
                            Gender = "Female",
                            LastName = "Demo",
                            LockoutEnabled = false,
                            NormalizedEmail = "USER11@HMS.COM",
                            NormalizedUserName = "USER11@HMS.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEOM2G8P9XkY5TzR7LqV3WpZ9mN1vXc8Q==",
                            PhoneNumber = "0300000011",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "a5580ec9-de9e-47bf-bd8a-5739b9c306e6",
                            TwoFactorEnabled = false,
                            UserName = "user11@hms.com"
                        },
                        new
                        {
                            Id = 12,
                            AccessFailedCount = 0,
                            Address = "Lahore, Pakistan",
                            Age = 30,
                            ConcurrencyStamp = "dfb6fd76-a89a-4cb6-a711-d2efe6bbc1c0",
                            Email = "user12@hms.com",
                            EmailConfirmed = true,
                            FirstName = "First12",
                            Gender = "Male",
                            LastName = "Demo",
                            LockoutEnabled = false,
                            NormalizedEmail = "USER12@HMS.COM",
                            NormalizedUserName = "USER12@HMS.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEOM2G8P9XkY5TzR7LqV3WpZ9mN1vXc8Q==",
                            PhoneNumber = "0300000012",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "c3a53a6a-3eab-4f3f-96c2-cbb61ac5e229",
                            TwoFactorEnabled = false,
                            UserName = "user12@hms.com"
                        },
                        new
                        {
                            Id = 13,
                            AccessFailedCount = 0,
                            Address = "Lahore, Pakistan",
                            Age = 31,
                            ConcurrencyStamp = "994d3b01-b86c-4b61-8585-081882b3f7cd",
                            Email = "user13@hms.com",
                            EmailConfirmed = true,
                            FirstName = "First13",
                            Gender = "Female",
                            LastName = "Demo",
                            LockoutEnabled = false,
                            NormalizedEmail = "USER13@HMS.COM",
                            NormalizedUserName = "USER13@HMS.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEOM2G8P9XkY5TzR7LqV3WpZ9mN1vXc8Q==",
                            PhoneNumber = "0300000013",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "83210488-b33b-41c6-ac41-25b73c0ff462",
                            TwoFactorEnabled = false,
                            UserName = "user13@hms.com"
                        },
                        new
                        {
                            Id = 14,
                            AccessFailedCount = 0,
                            Address = "Lahore, Pakistan",
                            Age = 32,
                            ConcurrencyStamp = "434b42cb-9172-449e-90f1-d86bb73db5fd",
                            Email = "user14@hms.com",
                            EmailConfirmed = true,
                            FirstName = "First14",
                            Gender = "Male",
                            LastName = "Demo",
                            LockoutEnabled = false,
                            NormalizedEmail = "USER14@HMS.COM",
                            NormalizedUserName = "USER14@HMS.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEOM2G8P9XkY5TzR7LqV3WpZ9mN1vXc8Q==",
                            PhoneNumber = "0300000014",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "77d98ba7-4063-4a86-8203-85da193adbb4",
                            TwoFactorEnabled = false,
                            UserName = "user14@hms.com"
                        },
                        new
                        {
                            Id = 15,
                            AccessFailedCount = 0,
                            Address = "Lahore, Pakistan",
                            Age = 33,
                            ConcurrencyStamp = "986a478f-f63e-44c4-a172-87290daf7b8c",
                            Email = "user15@hms.com",
                            EmailConfirmed = true,
                            FirstName = "First15",
                            Gender = "Female",
                            LastName = "Demo",
                            LockoutEnabled = false,
                            NormalizedEmail = "USER15@HMS.COM",
                            NormalizedUserName = "USER15@HMS.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEOM2G8P9XkY5TzR7LqV3WpZ9mN1vXc8Q==",
                            PhoneNumber = "0300000015",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "1a408be7-25f3-415b-916d-70b1051a4dff",
                            TwoFactorEnabled = false,
                            UserName = "user15@hms.com"
                        },
                        new
                        {
                            Id = 16,
                            AccessFailedCount = 0,
                            Address = "Lahore, Pakistan",
                            Age = 34,
                            ConcurrencyStamp = "d449e204-8044-45e5-91d9-69db18f2bee9",
                            Email = "user16@hms.com",
                            EmailConfirmed = true,
                            FirstName = "First16",
                            Gender = "Male",
                            LastName = "Demo",
                            LockoutEnabled = false,
                            NormalizedEmail = "USER16@HMS.COM",
                            NormalizedUserName = "USER16@HMS.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEOM2G8P9XkY5TzR7LqV3WpZ9mN1vXc8Q==",
                            PhoneNumber = "0300000016",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "e1cde4d4-551c-4f88-8588-61313cf64858",
                            TwoFactorEnabled = false,
                            UserName = "user16@hms.com"
                        },
                        new
                        {
                            Id = 17,
                            AccessFailedCount = 0,
                            Address = "Lahore, Pakistan",
                            Age = 35,
                            ConcurrencyStamp = "2e71dfe3-6ca3-463c-bb94-02e0571b29ec",
                            Email = "user17@hms.com",
                            EmailConfirmed = true,
                            FirstName = "First17",
                            Gender = "Female",
                            LastName = "Demo",
                            LockoutEnabled = false,
                            NormalizedEmail = "USER17@HMS.COM",
                            NormalizedUserName = "USER17@HMS.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEOM2G8P9XkY5TzR7LqV3WpZ9mN1vXc8Q==",
                            PhoneNumber = "0300000017",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "9baf40cf-8c38-4089-b541-36c01abfde56",
                            TwoFactorEnabled = false,
                            UserName = "user17@hms.com"
                        },
                        new
                        {
                            Id = 18,
                            AccessFailedCount = 0,
                            Address = "Lahore, Pakistan",
                            Age = 36,
                            ConcurrencyStamp = "1767fdba-5dc1-418b-9968-9275d64b03bf",
                            Email = "user18@hms.com",
                            EmailConfirmed = true,
                            FirstName = "First18",
                            Gender = "Male",
                            LastName = "Demo",
                            LockoutEnabled = false,
                            NormalizedEmail = "USER18@HMS.COM",
                            NormalizedUserName = "USER18@HMS.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEOM2G8P9XkY5TzR7LqV3WpZ9mN1vXc8Q==",
                            PhoneNumber = "0300000018",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "710bb229-b6b7-476c-8efb-f7e4201aad74",
                            TwoFactorEnabled = false,
                            UserName = "user18@hms.com"
                        },
                        new
                        {
                            Id = 19,
                            AccessFailedCount = 0,
                            Address = "Lahore, Pakistan",
                            Age = 37,
                            ConcurrencyStamp = "ef974141-67dd-413a-bd56-06509887b85a",
                            Email = "user19@hms.com",
                            EmailConfirmed = true,
                            FirstName = "First19",
                            Gender = "Female",
                            LastName = "Demo",
                            LockoutEnabled = false,
                            NormalizedEmail = "USER19@HMS.COM",
                            NormalizedUserName = "USER19@HMS.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEOM2G8P9XkY5TzR7LqV3WpZ9mN1vXc8Q==",
                            PhoneNumber = "0300000019",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "a0801042-b1a0-4f90-bb90-543b1c28b5f9",
                            TwoFactorEnabled = false,
                            UserName = "user19@hms.com"
                        },
                        new
                        {
                            Id = 20,
                            AccessFailedCount = 0,
                            Address = "Lahore, Pakistan",
                            Age = 38,
                            ConcurrencyStamp = "e4f879f2-f6df-4774-8aab-fbf69c5f992a",
                            Email = "user20@hms.com",
                            EmailConfirmed = true,
                            FirstName = "First20",
                            Gender = "Male",
                            LastName = "Demo",
                            LockoutEnabled = false,
                            NormalizedEmail = "USER20@HMS.COM",
                            NormalizedUserName = "USER20@HMS.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEOM2G8P9XkY5TzR7LqV3WpZ9mN1vXc8Q==",
                            PhoneNumber = "0300000020",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "627da467-a367-494c-b9a7-ad09f278a548",
                            TwoFactorEnabled = false,
                            UserName = "user20@hms.com"
                        },
                        new
                        {
                            Id = 21,
                            AccessFailedCount = 0,
                            Address = "Lahore, Pakistan",
                            Age = 39,
                            ConcurrencyStamp = "88535cdb-1bfc-4483-a085-fcfb73b7a6ca",
                            Email = "user21@hms.com",
                            EmailConfirmed = true,
                            FirstName = "First21",
                            Gender = "Female",
                            LastName = "Demo",
                            LockoutEnabled = false,
                            NormalizedEmail = "USER21@HMS.COM",
                            NormalizedUserName = "USER21@HMS.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEOM2G8P9XkY5TzR7LqV3WpZ9mN1vXc8Q==",
                            PhoneNumber = "0300000021",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "0e444a8b-fede-4c5b-b930-713b82652fb3",
                            TwoFactorEnabled = false,
                            UserName = "user21@hms.com"
                        },
                        new
                        {
                            Id = 22,
                            AccessFailedCount = 0,
                            Address = "Lahore, Pakistan",
                            Age = 40,
                            ConcurrencyStamp = "1a1f61d1-880e-4fa5-97d5-2ccca5a30358",
                            Email = "user22@hms.com",
                            EmailConfirmed = true,
                            FirstName = "First22",
                            Gender = "Male",
                            LastName = "Demo",
                            LockoutEnabled = false,
                            NormalizedEmail = "USER22@HMS.COM",
                            NormalizedUserName = "USER22@HMS.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEOM2G8P9XkY5TzR7LqV3WpZ9mN1vXc8Q==",
                            PhoneNumber = "0300000022",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "4a212fe5-aaad-4c93-90f2-2dce74702850",
                            TwoFactorEnabled = false,
                            UserName = "user22@hms.com"
                        },
                        new
                        {
                            Id = 23,
                            AccessFailedCount = 0,
                            Address = "Lahore, Pakistan",
                            Age = 41,
                            ConcurrencyStamp = "d5c47986-2654-4a99-8d75-681978c075c2",
                            Email = "user23@hms.com",
                            EmailConfirmed = true,
                            FirstName = "First23",
                            Gender = "Female",
                            LastName = "Demo",
                            LockoutEnabled = false,
                            NormalizedEmail = "USER23@HMS.COM",
                            NormalizedUserName = "USER23@HMS.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEOM2G8P9XkY5TzR7LqV3WpZ9mN1vXc8Q==",
                            PhoneNumber = "0300000023",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "44730c32-7294-4113-b011-623fbaa0116d",
                            TwoFactorEnabled = false,
                            UserName = "user23@hms.com"
                        },
                        new
                        {
                            Id = 24,
                            AccessFailedCount = 0,
                            Address = "Lahore, Pakistan",
                            Age = 42,
                            ConcurrencyStamp = "2c3c6fe8-6efb-459a-b09b-255054f3e1e3",
                            Email = "user24@hms.com",
                            EmailConfirmed = true,
                            FirstName = "First24",
                            Gender = "Male",
                            LastName = "Demo",
                            LockoutEnabled = false,
                            NormalizedEmail = "USER24@HMS.COM",
                            NormalizedUserName = "USER24@HMS.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEOM2G8P9XkY5TzR7LqV3WpZ9mN1vXc8Q==",
                            PhoneNumber = "0300000024",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "1cc938dc-5ae9-42da-bb54-66f0b686baee",
                            TwoFactorEnabled = false,
                            UserName = "user24@hms.com"
                        },
                        new
                        {
                            Id = 25,
                            AccessFailedCount = 0,
                            Address = "Lahore, Pakistan",
                            Age = 43,
                            ConcurrencyStamp = "185500dd-7f45-487c-b0c0-09a4cb138570",
                            Email = "user25@hms.com",
                            EmailConfirmed = true,
                            FirstName = "First25",
                            Gender = "Female",
                            LastName = "Demo",
                            LockoutEnabled = false,
                            NormalizedEmail = "USER25@HMS.COM",
                            NormalizedUserName = "USER25@HMS.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEOM2G8P9XkY5TzR7LqV3WpZ9mN1vXc8Q==",
                            PhoneNumber = "0300000025",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "050c80d3-c949-4d86-b262-076cebbf00fb",
                            TwoFactorEnabled = false,
                            UserName = "user25@hms.com"
                        },
                        new
                        {
                            Id = 26,
                            AccessFailedCount = 0,
                            Address = "Lahore, Pakistan",
                            Age = 44,
                            ConcurrencyStamp = "8659fd4b-36e1-4dbc-ba3b-ed8197b39a0c",
                            Email = "user26@hms.com",
                            EmailConfirmed = true,
                            FirstName = "First26",
                            Gender = "Male",
                            LastName = "Demo",
                            LockoutEnabled = false,
                            NormalizedEmail = "USER26@HMS.COM",
                            NormalizedUserName = "USER26@HMS.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEOM2G8P9XkY5TzR7LqV3WpZ9mN1vXc8Q==",
                            PhoneNumber = "0300000026",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "efb9d6e2-59fb-4c7f-bfb5-278ee313b86c",
                            TwoFactorEnabled = false,
                            UserName = "user26@hms.com"
                        },
                        new
                        {
                            Id = 27,
                            AccessFailedCount = 0,
                            Address = "Lahore, Pakistan",
                            Age = 45,
                            ConcurrencyStamp = "37e6d2c4-b005-442f-a477-e0f28664f760",
                            Email = "user27@hms.com",
                            EmailConfirmed = true,
                            FirstName = "First27",
                            Gender = "Female",
                            LastName = "Demo",
                            LockoutEnabled = false,
                            NormalizedEmail = "USER27@HMS.COM",
                            NormalizedUserName = "USER27@HMS.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEOM2G8P9XkY5TzR7LqV3WpZ9mN1vXc8Q==",
                            PhoneNumber = "0300000027",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "fdfdba08-e14a-49fa-814a-b66ee2488874",
                            TwoFactorEnabled = false,
                            UserName = "user27@hms.com"
                        },
                        new
                        {
                            Id = 28,
                            AccessFailedCount = 0,
                            Address = "Lahore, Pakistan",
                            Age = 46,
                            ConcurrencyStamp = "8a39b2f4-aa5e-402d-84fa-0e7a113cfdae",
                            Email = "user28@hms.com",
                            EmailConfirmed = true,
                            FirstName = "First28",
                            Gender = "Male",
                            LastName = "Demo",
                            LockoutEnabled = false,
                            NormalizedEmail = "USER28@HMS.COM",
                            NormalizedUserName = "USER28@HMS.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEOM2G8P9XkY5TzR7LqV3WpZ9mN1vXc8Q==",
                            PhoneNumber = "0300000028",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "d2770805-de21-4d9e-ae5b-10b54ebd52c4",
                            TwoFactorEnabled = false,
                            UserName = "user28@hms.com"
                        },
                        new
                        {
                            Id = 29,
                            AccessFailedCount = 0,
                            Address = "Lahore, Pakistan",
                            Age = 47,
                            ConcurrencyStamp = "b225b486-e56d-4450-9b0d-6990e9d6b0a4",
                            Email = "user29@hms.com",
                            EmailConfirmed = true,
                            FirstName = "First29",
                            Gender = "Female",
                            LastName = "Demo",
                            LockoutEnabled = false,
                            NormalizedEmail = "USER29@HMS.COM",
                            NormalizedUserName = "USER29@HMS.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEOM2G8P9XkY5TzR7LqV3WpZ9mN1vXc8Q==",
                            PhoneNumber = "0300000029",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "8a64c356-850e-4383-892f-ffdb495175b7",
                            TwoFactorEnabled = false,
                            UserName = "user29@hms.com"
                        },
                        new
                        {
                            Id = 30,
                            AccessFailedCount = 0,
                            Address = "Lahore, Pakistan",
                            Age = 48,
                            ConcurrencyStamp = "5776a74f-9b52-4d51-95a0-342b9e713d90",
                            Email = "user30@hms.com",
                            EmailConfirmed = true,
                            FirstName = "First30",
                            Gender = "Male",
                            LastName = "Demo",
                            LockoutEnabled = false,
                            NormalizedEmail = "USER30@HMS.COM",
                            NormalizedUserName = "USER30@HMS.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEOM2G8P9XkY5TzR7LqV3WpZ9mN1vXc8Q==",
                            PhoneNumber = "0300000030",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "cd21b591-11ac-4454-8659-4bfd6be6f42f",
                            TwoFactorEnabled = false,
                            UserName = "user30@hms.com"
                        });
                });

            modelBuilder.Entity("HospitalManagementSystem.Data.Models.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AppointmentDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.ToTable("Appointments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AppointmentDate = new DateTime(2025, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 1,
                            PatientId = 1,
                            Reason = "Routine checkup",
                            Status = "Confirmed"
                        },
                        new
                        {
                            Id = 2,
                            AppointmentDate = new DateTime(2025, 1, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 2,
                            PatientId = 2,
                            Reason = "Routine checkup",
                            Status = "Confirmed"
                        },
                        new
                        {
                            Id = 3,
                            AppointmentDate = new DateTime(2025, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 3,
                            PatientId = 3,
                            Reason = "Routine checkup",
                            Status = "Confirmed"
                        },
                        new
                        {
                            Id = 4,
                            AppointmentDate = new DateTime(2025, 1, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 4,
                            PatientId = 4,
                            Reason = "Routine checkup",
                            Status = "Confirmed"
                        },
                        new
                        {
                            Id = 5,
                            AppointmentDate = new DateTime(2025, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 5,
                            PatientId = 5,
                            Reason = "Routine checkup",
                            Status = "Confirmed"
                        });
                });

            modelBuilder.Entity("HospitalManagementSystem.Data.Models.Bed", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BedNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOccupied")
                        .HasColumnType("bit");

                    b.Property<int>("WardId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WardId");

                    b.ToTable("Beds");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BedNumber = "B-01",
                            IsDeleted = false,
                            IsOccupied = false,
                            WardId = 1
                        },
                        new
                        {
                            Id = 2,
                            BedNumber = "B-02",
                            IsDeleted = false,
                            IsOccupied = false,
                            WardId = 2
                        },
                        new
                        {
                            Id = 3,
                            BedNumber = "B-03",
                            IsDeleted = false,
                            IsOccupied = false,
                            WardId = 3
                        },
                        new
                        {
                            Id = 4,
                            BedNumber = "B-04",
                            IsDeleted = false,
                            IsOccupied = false,
                            WardId = 4
                        },
                        new
                        {
                            Id = 5,
                            BedNumber = "B-05",
                            IsDeleted = false,
                            IsOccupied = false,
                            WardId = 5
                        });
                });

            modelBuilder.Entity("HospitalManagementSystem.Data.Models.Bill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AppointmentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("BillingDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("bit");

                    b.Property<string>("PaymentMethod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Tax")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId");

                    b.ToTable("Bills");
                });

            modelBuilder.Entity("HospitalManagementSystem.Data.Models.BillItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("BillId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ReferenceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BillId");

                    b.ToTable("BillItems");
                });

            modelBuilder.Entity("HospitalManagementSystem.Data.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsDeleted = false,
                            Name = "Department 1"
                        },
                        new
                        {
                            Id = 2,
                            IsDeleted = false,
                            Name = "Department 2"
                        },
                        new
                        {
                            Id = 3,
                            IsDeleted = false,
                            Name = "Department 3"
                        },
                        new
                        {
                            Id = 4,
                            IsDeleted = false,
                            Name = "Department 4"
                        },
                        new
                        {
                            Id = 5,
                            IsDeleted = false,
                            Name = "Department 5"
                        });
                });

            modelBuilder.Entity("HospitalManagementSystem.Data.Models.Doctor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("ConsultationFee")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Qualification")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Doctors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConsultationFee = 2000m,
                            DepartmentId = 1,
                            Specialization = "Specialty 1",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            ConsultationFee = 2200m,
                            DepartmentId = 2,
                            Specialization = "Specialty 2",
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            ConsultationFee = 2400m,
                            DepartmentId = 3,
                            Specialization = "Specialty 3",
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            ConsultationFee = 2600m,
                            DepartmentId = 4,
                            Specialization = "Specialty 4",
                            UserId = 4
                        },
                        new
                        {
                            Id = 5,
                            ConsultationFee = 2800m,
                            DepartmentId = 5,
                            Specialization = "Specialty 5",
                            UserId = 5
                        });
                });

            modelBuilder.Entity("HospitalManagementSystem.Data.Models.LabReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("LabTestId")
                        .HasColumnType("int");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("ResultDetails")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TestDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("LabTestId");

                    b.HasIndex("PatientId");

                    b.ToTable("LabReports");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsDeleted = false,
                            LabTestId = 1,
                            PatientId = 1,
                            ResultDetails = "Within normal limits",
                            TestDate = new DateTime(2025, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            IsDeleted = false,
                            LabTestId = 2,
                            PatientId = 2,
                            ResultDetails = "Within normal limits",
                            TestDate = new DateTime(2025, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            IsDeleted = false,
                            LabTestId = 3,
                            PatientId = 3,
                            ResultDetails = "Within normal limits",
                            TestDate = new DateTime(2025, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            IsDeleted = false,
                            LabTestId = 4,
                            PatientId = 4,
                            ResultDetails = "Within normal limits",
                            TestDate = new DateTime(2025, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            IsDeleted = false,
                            LabTestId = 5,
                            PatientId = 5,
                            ResultDetails = "Within normal limits",
                            TestDate = new DateTime(2025, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("HospitalManagementSystem.Data.Models.LabTest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TestName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LabTests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsDeleted = false,
                            Price = 950m,
                            TestName = "Lab Test 1"
                        },
                        new
                        {
                            Id = 2,
                            IsDeleted = false,
                            Price = 1100m,
                            TestName = "Lab Test 2"
                        },
                        new
                        {
                            Id = 3,
                            IsDeleted = false,
                            Price = 1250m,
                            TestName = "Lab Test 3"
                        },
                        new
                        {
                            Id = 4,
                            IsDeleted = false,
                            Price = 1400m,
                            TestName = "Lab Test 4"
                        },
                        new
                        {
                            Id = 5,
                            IsDeleted = false,
                            Price = 1550m,
                            TestName = "Lab Test 5"
                        });
                });

            modelBuilder.Entity("HospitalManagementSystem.Data.Models.MedicalRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Diagnosis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("Symptoms")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TreatmentPlan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.ToTable("MedicalRecords");
                });

            modelBuilder.Entity("HospitalManagementSystem.Data.Models.Medicine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Medicines");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ExpiryDate = new DateTime(2027, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "Medicine 1",
                            StockQuantity = 200,
                            UnitPrice = 45.50m
                        },
                        new
                        {
                            Id = 2,
                            ExpiryDate = new DateTime(2027, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "Medicine 2",
                            StockQuantity = 200,
                            UnitPrice = 91.00m
                        },
                        new
                        {
                            Id = 3,
                            ExpiryDate = new DateTime(2027, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "Medicine 3",
                            StockQuantity = 200,
                            UnitPrice = 136.50m
                        },
                        new
                        {
                            Id = 4,
                            ExpiryDate = new DateTime(2027, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "Medicine 4",
                            StockQuantity = 200,
                            UnitPrice = 182.00m
                        },
                        new
                        {
                            Id = 5,
                            ExpiryDate = new DateTime(2027, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "Medicine 5",
                            StockQuantity = 200,
                            UnitPrice = 227.50m
                        });
                });

            modelBuilder.Entity("HospitalManagementSystem.Data.Models.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BloodGroup")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmergencyContact")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Patients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BloodGroup = "A+",
                            IsDeleted = false,
                            UserId = 11
                        },
                        new
                        {
                            Id = 2,
                            BloodGroup = "B+",
                            IsDeleted = false,
                            UserId = 12
                        },
                        new
                        {
                            Id = 3,
                            BloodGroup = "O+",
                            IsDeleted = false,
                            UserId = 13
                        },
                        new
                        {
                            Id = 4,
                            BloodGroup = "A+",
                            IsDeleted = false,
                            UserId = 14
                        },
                        new
                        {
                            Id = 5,
                            BloodGroup = "B+",
                            IsDeleted = false,
                            UserId = 15
                        });
                });

            modelBuilder.Entity("HospitalManagementSystem.Data.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("BillId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransactionId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BillId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("HospitalManagementSystem.Data.Models.Prescription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MedicalRecordId")
                        .HasColumnType("int");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PrescriptionDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.ToTable("Prescriptions");
                });

            modelBuilder.Entity("HospitalManagementSystem.Data.Models.PrescriptionItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Dosage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MedicineId")
                        .HasColumnType("int");

                    b.Property<int>("PrescriptionId")
                        .HasColumnType("int");

                    b.Property<decimal?>("PriceAtIssue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MedicineId");

                    b.HasIndex("PrescriptionId");

                    b.ToTable("PrescriptionItems");
                });

            modelBuilder.Entity("HospitalManagementSystem.Data.Models.Staff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal>("Salary")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("StaffMembers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Designation = "Technician",
                            IsDeleted = false,
                            Salary = 53000m,
                            UserId = 21
                        },
                        new
                        {
                            Id = 2,
                            Designation = "Nurse",
                            IsDeleted = false,
                            Salary = 58000m,
                            UserId = 22
                        },
                        new
                        {
                            Id = 3,
                            Designation = "Technician",
                            IsDeleted = false,
                            Salary = 63000m,
                            UserId = 23
                        },
                        new
                        {
                            Id = 4,
                            Designation = "Nurse",
                            IsDeleted = false,
                            Salary = 68000m,
                            UserId = 24
                        },
                        new
                        {
                            Id = 5,
                            Designation = "Technician",
                            IsDeleted = false,
                            Salary = 73000m,
                            UserId = 25
                        });
                });

            modelBuilder.Entity("HospitalManagementSystem.Data.Models.Ward", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalBeds")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Wards");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsDeleted = false,
                            Name = "Ward 1",
                            TotalBeds = 12,
                            Type = "Special"
                        },
                        new
                        {
                            Id = 2,
                            IsDeleted = false,
                            Name = "Ward 2",
                            TotalBeds = 12,
                            Type = "General"
                        },
                        new
                        {
                            Id = 3,
                            IsDeleted = false,
                            Name = "Ward 3",
                            TotalBeds = 12,
                            Type = "Special"
                        },
                        new
                        {
                            Id = 4,
                            IsDeleted = false,
                            Name = "Ward 4",
                            TotalBeds = 12,
                            Type = "General"
                        },
                        new
                        {
                            Id = 5,
                            IsDeleted = false,
                            Name = "Ward 5",
                            TotalBeds = 12,
                            Type = "Special"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Doctor",
                            NormalizedName = "DOCTOR"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Patient",
                            NormalizedName = "PATIENT"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Staff",
                            NormalizedName = "STAFF"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = 31,
                            RoleId = 1
                        },
                        new
                        {
                            UserId = 1,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 2,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 3,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 4,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 5,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 6,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 7,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 8,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 9,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 10,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 11,
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 12,
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 13,
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 14,
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 15,
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 16,
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 17,
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 18,
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 19,
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 20,
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 21,
                            RoleId = 4
                        },
                        new
                        {
                            UserId = 22,
                            RoleId = 4
                        },
                        new
                        {
                            UserId = 23,
                            RoleId = 4
                        },
                        new
                        {
                            UserId = 24,
                            RoleId = 4
                        },
                        new
                        {
                            UserId = 25,
                            RoleId = 4
                        },
                        new
                        {
                            UserId = 26,
                            RoleId = 4
                        },
                        new
                        {
                            UserId = 27,
                            RoleId = 4
                        },
                        new
                        {
                            UserId = 28,
                            RoleId = 4
                        },
                        new
                        {
                            UserId = 29,
                            RoleId = 4
                        },
                        new
                        {
                            UserId = 30,
                            RoleId = 4
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("HospitalManagementSystem.Data.Models.Admission", b =>
                {
                    b.HasOne("HospitalManagementSystem.Data.Models.Bed", "Bed")
                        .WithMany("Admissions")
                        .HasForeignKey("BedId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HospitalManagementSystem.Data.Models.Patient", "Patient")
                        .WithMany("Admissions")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Bed");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("HospitalManagementSystem.Data.Models.Appointment", b =>
                {
                    b.HasOne("HospitalManagementSystem.Data.Models.Doctor", "Doctor")
                        .WithMany("Appointments")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HospitalManagementSystem.Data.Models.Patient", "Patient")
                        .WithMany("Appointments")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("HospitalManagementSystem.Data.Models.Bed", b =>
                {
                    b.HasOne("HospitalManagementSystem.Data.Models.Ward", "Ward")
                        .WithMany("Beds")
                        .HasForeignKey("WardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ward");
                });

            modelBuilder.Entity("HospitalManagementSystem.Data.Models.Bill", b =>
                {
                    b.HasOne("HospitalManagementSystem.Data.Models.Appointment", "Appointment")
                        .WithMany()
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Appointment");
                });

            modelBuilder.Entity("HospitalManagementSystem.Data.Models.BillItem", b =>
                {
                    b.HasOne("HospitalManagementSystem.Data.Models.Bill", "Bill")
                        .WithMany("Items")
                        .HasForeignKey("BillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bill");
                });

            modelBuilder.Entity("HospitalManagementSystem.Data.Models.Doctor", b =>
                {
                    b.HasOne("HospitalManagementSystem.Data.Models.Department", "Department")
                        .WithMany("Doctors")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HospitalManagementSystem.Data.Models.ApplicationUser", "User")
                        .WithOne()
                        .HasForeignKey("HospitalManagementSystem.Data.Models.Doctor", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HospitalManagementSystem.Data.Models.LabReport", b =>
                {
                    b.HasOne("HospitalManagementSystem.Data.Models.LabTest", "LabTest")
                        .WithMany()
                        .HasForeignKey("LabTestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HospitalManagementSystem.Data.Models.Patient", "Patient")
                        .WithMany("LabReports")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LabTest");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("HospitalManagementSystem.Data.Models.MedicalRecord", b =>
                {
                    b.HasOne("HospitalManagementSystem.Data.Models.Doctor", "Doctor")
                        .WithMany("MedicalRecords")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HospitalManagementSystem.Data.Models.Patient", "Patient")
                        .WithMany("MedicalRecords")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("HospitalManagementSystem.Data.Models.Patient", b =>
                {
                    b.HasOne("HospitalManagementSystem.Data.Models.ApplicationUser", "User")
                        .WithOne()
                        .HasForeignKey("HospitalManagementSystem.Data.Models.Patient", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HospitalManagementSystem.Data.Models.Payment", b =>
                {
                    b.HasOne("HospitalManagementSystem.Data.Models.Bill", "Bill")
                        .WithMany("Payments")
                        .HasForeignKey("BillId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Bill");
                });

            modelBuilder.Entity("HospitalManagementSystem.Data.Models.Prescription", b =>
                {
                    b.HasOne("HospitalManagementSystem.Data.Models.Doctor", "Doctor")
                        .WithMany("Prescriptions")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HospitalManagementSystem.Data.Models.Patient", "Patient")
                        .WithMany("Prescriptions")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("HospitalManagementSystem.Data.Models.PrescriptionItem", b =>
                {
                    b.HasOne("HospitalManagementSystem.Data.Models.Medicine", "Medicine")
                        .WithMany()
                        .HasForeignKey("MedicineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HospitalManagementSystem.Data.Models.Prescription", "Prescription")
                        .WithMany("Items")
                        .HasForeignKey("PrescriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Medicine");

                    b.Navigation("Prescription");
                });

            modelBuilder.Entity("HospitalManagementSystem.Data.Models.Staff", b =>
                {
                    b.HasOne("HospitalManagementSystem.Data.Models.ApplicationUser", "User")
                        .WithOne()
                        .HasForeignKey("HospitalManagementSystem.Data.Models.Staff", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("HospitalManagementSystem.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("HospitalManagementSystem.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HospitalManagementSystem.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("HospitalManagementSystem.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HospitalManagementSystem.Data.Models.Bed", b =>
                {
                    b.Navigation("Admissions");
                });

            modelBuilder.Entity("HospitalManagementSystem.Data.Models.Bill", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("HospitalManagementSystem.Data.Models.Department", b =>
                {
                    b.Navigation("Doctors");
                });

            modelBuilder.Entity("HospitalManagementSystem.Data.Models.Doctor", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("MedicalRecords");

                    b.Navigation("Prescriptions");
                });

            modelBuilder.Entity("HospitalManagementSystem.Data.Models.Patient", b =>
                {
                    b.Navigation("Admissions");

                    b.Navigation("Appointments");

                    b.Navigation("LabReports");

                    b.Navigation("MedicalRecords");

                    b.Navigation("Prescriptions");
                });

            modelBuilder.Entity("HospitalManagementSystem.Data.Models.Prescription", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("HospitalManagementSystem.Data.Models.Ward", b =>
                {
                    b.Navigation("Beds");
                });
#pragma warning restore 612, 618
        }
    }
}
